In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load our working dataset
df = pd.read_parquet("../data/interim/all_beauty_sample.parquet")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

Dataset loaded successfully!
Shape: (20000, 16)

In [3]:
df_clean = df.copy()

In [5]:
df_clean.shape

(20000, 16)

In [6]:
df_clean.head()

,rating,title_review,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,main_category,title_product,average_rating,rating_number,price,store,details
0,5.0,Neon pink.,"Nice formula, smooth application with no pooli...",B00JQRPB9I,B00JQRPB9I,AFH5GZTYBKKGZ7SB45FUFLNWMUFQ,1431209081000,4,True,All Beauty,"Gelaze Gel-N-Base Polish, Shocking Pink, 0.5 F...",4.0,18,16.45,China Glaze,"{""Brand"": ""China Glaze"", ""Item Form"": ""Gel"", ""..."
1,5.0,Godd experience,Great product. It came when expected.,B00QHB48M2,B00QHB48M2,AFGLKF5GMQ3CYUBB2KFCODKBOEYA,1496279099000,0,True,All Beauty,Max Factor Panstik Foundation - 12 True Beige ...,4.8,325,None,Max Factor,"{""Item Form"": ""Stick"", ""Color"": ""Beige"", ""Pack..."
2,5.0,Love This..made my mom's day,My 90 year old mother's favorite fragrance.,B01IAFGDYS,B01IAFGDYS,AFTDHU6IXXYGCEJ6JUAI7LFD3JMA,1561392844340,0,True,All Beauty,Five Star Royal Secret Eau De Toilette Spray 1...,4.3,7,None,Five Star,"{""Brand"": ""Five Star"", ""Item Form"": ""Spray"", ""..."
3,1.0,Review,Just not worth it,B01DX9HUP2,B01DX9HUP2,AGIEEQAKFGKN7JH4LQKRWTCCMXGA,1497560837278,0,True,All Beauty,Buytra 20-Piece Makeup Brushes Makeup Brush Se...,3.9,239,None,Buytra,"{""Brand"": ""Buytra"", ""Recommended Uses For Prod..."
4,5.0,Battery will not stay charged (Rescinding),The Battery life on this product has always be...,B07W11NLFS,B07W11NLFS,AFNEEMO6DSJJTMBCIF3SCXUQBH2A,1580137117959,1,True,All Beauty,Cordless Water Flosser for Teeth-4 Preprogramm...,4.2,574,None,Duomishu,"{""Brand"": ""Duomishu"", ""Power Source"": ""Battery..."

In [7]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating             20000 non-null  float64
 1   title_review       20000 non-null  str
 2   text               20000 non-null  str
 3   asin               20000 non-null  str
 4   parent_asin        20000 non-null  str
 5   user_id            20000 non-null  str
 6   timestamp          20000 non-null  int64
 7   helpful_vote       20000 non-null  int64
 8   verified_purchase  20000 non-null  bool
 9   main_category      20000 non-null  str
 10  title_product      20000 non-null  str
 11  average_rating     20000 non-null  float64
 12  rating_number      20000 non-null  int64
 13  price              20000 non-null  str
 14  store              18571 non-null  str
 15  details            20000 non-null  str
dtypes: bool(1), float64(2), int64(3), str(10)
memory usage: 13.8 MB

In [8]:
df_clean.columns.tolist()

['rating',
 'title_review',
 'text',
 'asin',
 'parent_asin',
 'user_id',
 'timestamp',
 'helpful_vote',
 'verified_purchase',
 'main_category',
 'title_product',
 'average_rating',
 'rating_number',
 'price',
 'store',
 'details']

In [9]:
df_clean.duplicated().sum()

np.int64(9)

In [10]:
df_clean[df_clean.duplicated(keep=False)]

,rating,title_review,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,main_category,title_product,average_rating,rating_number,price,store,details
1968,1.0,Very DISAPPOINTED. If I could give it negative...,This looks like some cheap toy you would just ...,B009CA7BWO,B009CA7BWO,AHBQQ2SZJLEFOSC4FNP5BYP2IT5Q,1544215794267,7,True,All Beauty,Smudger Healing Secret 5 Feathers by New Age,3.6,151,17.5,New Age,"{""Is Discontinued By Manufacturer"": ""No"", ""Pac..."
3064,5.0,I have a lot of hair in my head,Perfect,B07WN2RNT3,B07WN2RNT3,AF5U6NKHIM7RUUZY4TTGJ4MEZ7GQ,1615345733836,1,True,All Beauty,SAYMRE Large Satin Hair Bonnet Sleep Cap Elast...,4.3,88,None,SAYMRE,"{""Product Dimensions"": ""8.5 x 6.5 x 0.55 inche..."
3346,3.0,Lasted two years,"I liked the brush while it lasted. However, ...",B01E3MF6KE,B01E3MF6KE,AHKOKSXYQKKUB7W2ZJ4J3ZZM7GGA,1553751680151,0,True,All Beauty,"Bath Brush, Bamboo Bath Brush for Back Scrubbe...",4.0,378,None,Esarora,"{""Material"": ""Boar bristle, Bamboo"", ""Brand"": ..."
4231,5.0,Good,Goid,B07Y5VPGGN,B07Y5VPGGN,AFVCLWO7VGE26XIBNXIWF4PFEHWA,1593873435765,0,True,All Beauty,Newcally False Eyelashes 10 Pairs 3D Faux Mink...,4.2,64,None,Newcally,"{""Brand"": ""Newcally"", ""Material"": ""Faux Mink"",..."
6813,5.0,Would buy again!,Love these headbands! Perfect for us with larg...,B07MQ4L9P5,B07MQ4L9P5,AECEA2NFZUFEEFVEX7K3GPVMBPJQ,1564344819328,0,True,All Beauty,TAIHA 10 Pack Boho Headbands for Women Vintage...,3.9,19,None,Lorfancy,"{""Color"": ""K: 10 Pack ( Dot, Flower, Strip, Bo..."
7677,5.0,Perfect!,This is exactly what I wanted!,B07VJYXYDW,B07VJYXYDW,AG2XZNQ4F7DO4NHTIXRW4GL2YQIQ,1582488425150,0,True,All Beauty,"AOPRIE Pearl Headbands for Women, Elegant Faux...",3.6,2,None,AOPRIE,"{""Material"": ""pearl"", ""Brand"": ""AOPRIE"", ""Unit..."
8840,4.0,"meh not bad, not good","I like it I used the whole cream, I did not re...",B00HLRS44O,B00HLRS43U,AFNZTWQNJR5ULPBOMJTUPSNOZMFA,1457100208000,4,True,All Beauty,Japan 100gram 3Cup Size Must Up Breast & Butt ...,3.2,10,27.99,Must Up,"{""Item Form"": ""Cream"", ""Skin Type"": ""All"", ""It..."
10570,5.0,Good,Goid,B07Y5VPGGN,B07Y5VPGGN,AFVCLWO7VGE26XIBNXIWF4PFEHWA,1593873435765,0,True,All Beauty,Newcally False Eyelashes 10 Pairs 3D Faux Mink...,4.2,64,None,Newcally,"{""Brand"": ""Newcally"", ""Material"": ""Faux Mink"",..."
10979,5.0,Would buy again!,Love these headbands! Perfect for us with larg...,B07MQ4L9P5,B07MQ4L9P5,AECEA2NFZUFEEFVEX7K3GPVMBPJQ,1564344819328,0,True,All Beauty,TAIHA 10 Pack Boho Headbands for Women Vintage...,3.9,19,None,Lorfancy,"{""Color"": ""K: 10 Pack ( Dot, Flower, Strip, Bo..."
11449,5.0,"This is a good product, but the price is too high",I have been using this product for years as an...,B07HZ4CW7F,B07HZ4CW7F,AFOSF3NPSSHOBPID6SOYJWIJYJ2Q,1587246426777,11,True,All Beauty,"Soft & Dri, Aerosol, Antiperspirant Deodorant,...",4.8,1661,None,Soft & Dri,"{""Brand"": ""Soft & Dri"", ""Item Form"": ""Spray"", ..."
12452,1.0,Very DISAPPOINTED. If I could give it negative...,This looks like some cheap toy you would just ...,B009CA7BWO,B009CA7BWO,AHBQQ2SZJLEFOSC4FNP5BYP2IT5Q,1544215794267,7,True,All Beauty,Smudger Healing Secret 5 Feathers by New Age,3.6,151,17.5,New Age,"{""Is Discontinued By Manufacturer"": ""No"", ""Pac..."
12952,3.0,Lasted two years,"I liked the brush while it lasted. However, ...",B01E3MF6KE,B01E3MF6KE,AHKOKSXYQKKUB7W2ZJ4J3ZZM7GGA,1553751680151,0,True,All Beauty,"Bath Brush, Bamboo Bath Brush for Back Scrubbe...",4.0,378,None,Esarora,"{""Material"": ""Boar bristle, Bamboo"", ""Brand"": ..."
13043,5.0,"This is a good product, but the price is too high",I have been using this product for years as an...,B07HZ4CW7F,B07HZ4CW7F,AFOSF3NPSSHOBPID6SOYJWIJYJ2Q,1587246426777,11,True,All Beauty,"Soft & Dri, Aerosol, Antiperspirant Deodorant,...",4.8,1661,None,Soft & Dri,"{""Brand"": ""Soft & Dri"", ""Item Form"": ""Spray"", ..."
13159,5.0,I have a lot of hair in my head,Perfect,B07WN2RNT3,B07WN2RNT3,AF5U6NKHIM7RUUZY4TTGJ4MEZ7GQ,1615345733836,1,True,All Beauty,SAYMRE Large Satin Hair Bonnet Sleep Cap Elast...,4.3,88,None,SAYMRE,"{""Product Dimensions"": ""8.5 x 6.5 x 0.55 inche..."
14817,4.0,"meh not bad, not good","I like it I used the whole cream, I did not re...",B00HLRS44O,B00HLRS43U,AFNZTWQNJR5ULPBOMJTUPSNOZMFA,1457100208000,4,True,All Beauty,Japan 100gram 3Cup Size Must Up Breast & Butt ...,3.2,10,27.99,Must Up,"{""Item Form"": ""Cream"", ""Skin Type"": ""All"", ""It..."
16503,5.0,Perfect!,This is exactly what I wanted!,B07VJYXYDW,B07VJYXYDW,AG2XZNQ4F7DO4NHTIXRW4GL2YQIQ,1582488425150,0,True,All Beauty,"AOPRIE Pearl Headbands for Women, Elegant Faux...",3.6,2,None,AOPRIE,"{""Material"": ""pearl"", ""Brand"": ""AOPRIE"", ""Unit..."
16657,5.0,Would buy again!,Love these headbands! Perfect for us with larg...,B07MQ4L9P5,B07MQ4L9P5,AECEA2NFZUFEEFVEX7K3GPVMBPJQ,1564344819328,0,True,All Beauty,TAIHA 10 Pack Boho Headbands for Women Vintage...,3.9,19,None,Lorfancy,"{""Color"": ""K: 10 Pack ( Dot, Flower, Strip, Bo..."

In [11]:
df_clean.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
19995    False
19996    False
19997    False
19998    False
19999    False
Length: 20000, dtype: bool

In [13]:
df_clean = df_clean.drop_duplicates().copy()

In [14]:
df_clean.duplicated().sum()

np.int64(0)

In [15]:
df_clean.shape

(19991, 16)

In [16]:
df_clean.duplicated().sum()

np.int64(0)

In [17]:
df_clean[df_clean.duplicated(keep=False)]

Empty DataFrame
Columns: [rating, title_review, text, asin, parent_asin, user_id, timestamp, helpful_vote, verified_purchase, main_category, title_product, average_rating, rating_number, price, store, details]
Index: []

In [18]:
df_clean = df_clean.drop_duplicates().copy()

In [19]:
df_clean.shape

(19991, 16)

In [20]:
df_clean.isna().sum()

rating                  0
title_review            0
text                    0
asin                    0
parent_asin             0
user_id                 0
timestamp               0
helpful_vote            0
verified_purchase       0
main_category           0
title_product           0
average_rating          0
rating_number           0
price                   0
store                1429
details                 0
dtype: int64

In [21]:
missing_summary = pd.DataFrame({
    "missing_count": df_clean.isna().sum(),
    "missing_percentage": df_clean.isna().mean() * 100
})

missing_summary = missing_summary[
    missing_summary["missing_count"] > 0
].sort_values("missing_count", ascending=False)

missing_summary

       missing_count  missing_percentage
store           1429            7.148217

In [22]:
df_clean.isna().sum()

rating                  0
title_review            0
text                    0
asin                    0
parent_asin             0
user_id                 0
timestamp               0
helpful_vote            0
verified_purchase       0
main_category           0
title_product           0
average_rating          0
rating_number           0
price                   0
store                1429
details                 0
dtype: int64

In [23]:
missing_summary = pd.DataFrame({
    "missing_count": df_clean.isna().sum(),
    "missing_percentage": df_clean.isna().mean() * 100
})

missing_summary = missing_summary[
    missing_summary["missing_count"] > 0
].sort_values("missing_count", ascending=False)

missing_summary

       missing_count  missing_percentage
store           1429            7.148217

In [24]:
df_clean["store"].value_counts(dropna=False).head(20)

store
NaN                  1429
PHILIPS                87
Premium Nature         66
WILLBOND               62
Godefroy               62
Lume                   60
YMHPRIDE               59
Bath & Body Works      59
Segbeauty              57
AVON                   52
Soft 'N Style          51
Teenitor               48
Philips Norelco        48
KISS                   44
Tarte                  44
Lunana Beauty          43
SALUX                  42
Bed Head               41
Harlorki               40
JIMIRE                 40
Name: count, dtype: int64

In [25]:
df_clean["store"] = df_clean["store"].fillna("Unknown")

In [26]:
df_clean["store"].isna().sum()

np.int64(0)

In [27]:
df_clean["store"].value_counts().head(10)

store
Unknown              1468
PHILIPS                87
Premium Nature         66
WILLBOND               62
Godefroy               62
Lume                   60
YMHPRIDE               59
Bath & Body Works      59
Segbeauty              57
AVON                   52
Name: count, dtype: int64

In [28]:
df_clean.isna().sum()

rating               0
title_review         0
text                 0
asin                 0
parent_asin          0
user_id              0
timestamp            0
helpful_vote         0
verified_purchase    0
main_category        0
title_product        0
average_rating       0
rating_number        0
price                0
store                0
details              0
dtype: int64

In [29]:
df_clean["store"].value_counts(dropna=False).head(20)

store
Unknown              1468
PHILIPS                87
Premium Nature         66
WILLBOND               62
Godefroy               62
Lume                   60
YMHPRIDE               59
Bath & Body Works      59
Segbeauty              57
AVON                   52
Soft 'N Style          51
Teenitor               48
Philips Norelco        48
KISS                   44
Tarte                  44
Lunana Beauty          43
SALUX                  42
Bed Head               41
Harlorki               40
JIMIRE                 40
Name: count, dtype: int64

In [30]:
df_clean["store"] = df_clean["store"].fillna("Unknown")

In [31]:
df_clean["store"].isna().sum()

np.int64(0)

In [32]:
df_clean.isna().sum()

rating               0
title_review         0
text                 0
asin                 0
parent_asin          0
user_id              0
timestamp            0
helpful_vote         0
verified_purchase    0
main_category        0
title_product        0
average_rating       0
rating_number        0
price                0
store                0
details              0
dtype: int64

In [33]:
df_clean["store"] = df_clean["store"].fillna("Unknown")

In [34]:
df_clean.isna().sum()

rating               0
title_review         0
text                 0
asin                 0
parent_asin          0
user_id              0
timestamp            0
helpful_vote         0
verified_purchase    0
main_category        0
title_product        0
average_rating       0
rating_number        0
price                0
store                0
details              0
dtype: int64

In [36]:
(df_clean["text"].astype(str).str.strip() == "").sum()

np.int64(18)

In [37]:
(df_clean["title_review"].astype(str).str.strip() == "").sum()

np.int64(0)

In [38]:
empty_text = df_clean["text"].astype(str).str.strip() == ""
empty_title = df_clean["title_review"].astype(str).str.strip() == ""

(empty_text & empty_title).sum()

np.int64(0)

In [39]:
df_clean["rating"].value_counts().sort_index()

rating
1.0     2912
2.0     1234
3.0     1530
4.0     2295
5.0    12020
Name: count, dtype: int64

In [40]:
df_clean["rating"].min(), df_clean["rating"].max()

(np.float64(1.0), np.float64(5.0))

In [41]:
invalid_ratings = df_clean[
    (df_clean["rating"] < 1) |
    (df_clean["rating"] > 5)
]

invalid_ratings.shape

(0, 16)

In [42]:
df_clean["rating"].dtype

dtype('float64')

In [43]:
df_clean["helpful_vote"].describe()

count    19991.000000
mean         0.937872
std          6.021650
min          0.000000
25%          0.000000
50%          0.000000
75%          1.000000
max        430.000000
Name: helpful_vote, dtype: float64

In [44]:
(df_clean["helpful_vote"] < 0).sum()

np.int64(0)

In [45]:
df_clean["helpful_vote"].dtype

dtype('int64')

In [46]:
df_clean["helpful_vote"].isna().sum()

np.int64(0)

In [47]:
df_clean["verified_purchase"].value_counts(dropna=False)

verified_purchase
True     18148
False     1843
Name: count, dtype: int64

In [48]:
df_clean["verified_purchase"].dtype

dtype('bool')

In [49]:
df_clean["verified_purchase"].unique()

array([ True, False])

In [50]:
df_clean["verified_purchase"].isna().sum()

np.int64(0)

In [51]:
df_clean["parent_asin"].isna().sum()

np.int64(0)

In [52]:
df_clean["parent_asin"].nunique()

12923

In [53]:
df_clean["asin"].isna().sum()

np.int64(0)

In [54]:
df_clean["parent_asin"].isna().sum()

np.int64(0)

In [55]:
df_clean["parent_asin"].nunique()

12923

In [56]:
df_clean["asin"].isna().sum()

np.int64(0)

In [57]:
df_clean["asin"].nunique()

13227

In [59]:
df_clean["parent_asin"].isna().sum()

np.int64(0)

In [60]:
df_clean["parent_asin"].nunique()

12923

In [61]:
df_clean["asin"].isna().sum()

np.int64(0)

In [62]:
df_clean["asin"].nunique()

13227

In [63]:
df_clean.dtypes

rating               float64
title_review             str
text                     str
asin                     str
parent_asin              str
user_id                  str
timestamp              int64
helpful_vote           int64
verified_purchase       bool
main_category            str
title_product            str
average_rating       float64
rating_number          int64
price                    str
store                    str
details                  str
dtype: object

In [64]:
df_clean["timestamp"].head(10)

0    1431209081000
1    1496279099000
2    1561392844340
3    1497560837278
4    1580137117959
5    1474075105000
6    1449095206000
7    1607271273006
8    1600477187716
9    1579706774495
Name: timestamp, dtype: int64

In [65]:
df_clean["timestamp"].describe()

count    1.999100e+04
mean     1.555323e+12
std      7.993603e+10
min      1.083383e+12
25%      1.502744e+12
50%      1.571862e+12
75%      1.614958e+12
max      1.693533e+12
Name: timestamp, dtype: float64

In [66]:
df_clean["timestamp"].min(), df_clean["timestamp"].max()

(np.int64(1083383273000), np.int64(1693532791215))

In [67]:
df_clean["timestamp"].head(10)

0    1431209081000
1    1496279099000
2    1561392844340
3    1497560837278
4    1580137117959
5    1474075105000
6    1449095206000
7    1607271273006
8    1600477187716
9    1579706774495
Name: timestamp, dtype: int64

In [68]:
df_clean["timestamp"].describe()

count    1.999100e+04
mean     1.555323e+12
std      7.993603e+10
min      1.083383e+12
25%      1.502744e+12
50%      1.571862e+12
75%      1.614958e+12
max      1.693533e+12
Name: timestamp, dtype: float64

In [69]:
df_clean["timestamp"].min(), df_clean["timestamp"].max()

(np.int64(1083383273000), np.int64(1693532791215))

In [70]:
df_clean["timestamp"] = pd.to_datetime(
    df_clean["timestamp"],
    unit="ms"
)

In [71]:
df_clean["timestamp"].head()

0   2015-05-09 22:04:41.000
1   2017-06-01 01:04:59.000
2   2019-06-24 16:14:04.340
3   2017-06-15 21:07:17.278
4   2020-01-27 14:58:37.959
Name: timestamp, dtype: datetime64[ms]

In [72]:
df_clean["timestamp"].dtype

dtype('<M8[ms]')

In [73]:
df_clean["timestamp"].isna().sum()

np.int64(0)

In [74]:
df_clean["review_year"] = df_clean["timestamp"].dt.year
df_clean["review_month"] = df_clean["timestamp"].dt.month
df_clean["review_day"] = df_clean["timestamp"].dt.day
df_clean["review_day_of_week"] = df_clean["timestamp"].dt.dayofweek
df_clean["review_hour"] = df_clean["timestamp"].dt.hour

In [75]:
df_clean[
    [
        "timestamp",
        "review_year",
        "review_month",
        "review_day",
        "review_day_of_week",
        "review_hour"
    ]
].head()

,timestamp,review_year,review_month,review_day,review_day_of_week,review_hour
0,2015-05-09 22:04:41.000,2015,5,9,5,22
1,2017-06-01 01:04:59.000,2017,6,1,3,1
2,2019-06-24 16:14:04.340,2019,6,24,0,16
3,2017-06-15 21:07:17.278,2017,6,15,3,21
4,2020-01-27 14:58:37.959,2020,1,27,0,14

In [76]:
df_clean["price"].head(20)

0     16.45
1      None
2      None
3      None
4      None
5      None
6      6.85
7     11.99
8      None
9      None
10     7.99
11     None
12     None
13     None
14     None
15    17.99
16    10.21
17     None
18     None
19     None
Name: price, dtype: str

In [77]:
df_clean["price"].dtype

In [78]:
df_clean["price"].value_counts(dropna=False).head(20)

price
None     14729
9.99       249
11.99      153
12.99      148
6.99       122
7.99       118
14.99      117
16.99      110
19.99      101
24.95       99
15.99       96
8.99        83
27.99       79
13.99       67
24.99       60
4.99        59
5.99        56
23.99       49
18.99       46
10.99       42
Name: count, dtype: int64

In [79]:
df_clean["price"].dtype

In [80]:
df_clean["price"].isna().sum()

np.int64(0)

In [81]:
df_clean["price"].map(type).value_counts()

price
<class 'str'>    19991
Name: count, dtype: int64

In [82]:
df_clean["price"].value_counts().head(10)

price
None     14729
9.99       249
11.99      153
12.99      148
6.99       122
7.99       118
14.99      117
16.99      110
19.99      101
24.95       99
Name: count, dtype: int64

In [83]:
df_clean["price"] = df_clean["price"].replace("None", np.nan)

In [84]:
df_clean["price"].isna().sum()

np.int64(14729)

In [85]:
df_clean["price"] = pd.to_numeric(
    df_clean["price"],
    errors="coerce"
)

In [86]:
df_clean["price"].dtype

dtype('float64')

In [87]:
df_clean["price"].isna().sum()

np.int64(14729)

In [88]:
df_clean["price"].describe()

count    5262.000000
mean       23.297322
std        32.357107
min         1.000000
25%         9.990000
50%        15.990000
75%        25.000000
max      1185.720000
Name: price, dtype: float64

In [89]:
df_clean["price_available"] = df_clean["price"].notna()

In [90]:
df_clean["price_available"].value_counts()

price_available
False    14729
True      5262
Name: count, dtype: int64

In [92]:
df_clean["price"].dtype

dtype('float64')

In [93]:
df_clean["price"].isna().sum()

np.int64(14729)

In [94]:
df_clean["price_available"].value_counts()

price_available
False    14729
True      5262
Name: count, dtype: int64

In [95]:
df_clean["price"].min(), df_clean["price"].max()

(np.float64(1.0), np.float64(1185.72))

In [96]:
(df_clean["price"] < 0).sum()

np.int64(0)

In [97]:
(df_clean["price"] == 0).sum()

np.int64(0)

In [98]:
df_clean["price"].dropna().sort_values().head(20)

14650    1.00
14332    1.00
4166     1.20
696      1.20
19246    1.39
4178     1.49
18978    1.93
14218    1.99
2450     1.99
10426    2.29
13000    2.29
16494    2.29
16142    2.29
6215     2.29
12642    2.29
6041     2.88
6387     2.88
5471     2.89
17940    2.95
18083    2.95
Name: price, dtype: float64

In [99]:
df_clean["price"].dropna().sort_values(ascending=False).head(20)

3923     1185.72
10925     477.06
5124      334.99
3338      325.00
6446      319.95
2016      319.95
1980      319.95
13687     315.00
10348     300.00
5956      289.00
26        289.00
14354     279.99
120       273.38
17235     273.38
4251      273.38
4695      273.38
4752      273.38
19690     273.38
15739     273.38
18119     243.99
Name: price, dtype: float64

In [100]:
df_clean.dtypes

rating                       float64
title_review                     str
text                             str
asin                             str
parent_asin                      str
user_id                          str
timestamp             datetime64[ms]
helpful_vote                   int64
verified_purchase               bool
main_category                    str
title_product                    str
average_rating               float64
rating_number                  int64
price                        float64
store                            str
details                          str
review_year                    int32
review_month                   int32
review_day                     int32
review_day_of_week             int32
review_hour                    int32
price_available                 bool
dtype: object

In [101]:
df_clean.isna().sum()

rating                    0
title_review              0
text                      0
asin                      0
parent_asin               0
user_id                   0
timestamp                 0
helpful_vote              0
verified_purchase         0
main_category             0
title_product             0
average_rating            0
rating_number             0
price                 14729
store                     0
details                   0
review_year               0
review_month              0
review_day                0
review_day_of_week        0
review_hour               0
price_available           0
dtype: int64

In [102]:
df_clean.duplicated().sum()

np.int64(0)

In [103]:
df_clean.shape

(19991, 22)

In [104]:
df_clean.head()

,rating,title_review,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,main_category,...,rating_number,price,store,details,review_year,review_month,review_day,review_day_of_week,review_hour,price_available
0,5.0,Neon pink.,"Nice formula, smooth application with no pooli...",B00JQRPB9I,B00JQRPB9I,AFH5GZTYBKKGZ7SB45FUFLNWMUFQ,2015-05-09 22:04:41.000,4,True,All Beauty,...,18,16.45,China Glaze,"{""Brand"": ""China Glaze"", ""Item Form"": ""Gel"", ""...",2015,5,9,5,22,True
1,5.0,Godd experience,Great product. It came when expected.,B00QHB48M2,B00QHB48M2,AFGLKF5GMQ3CYUBB2KFCODKBOEYA,2017-06-01 01:04:59.000,0,True,All Beauty,...,325,NaN,Max Factor,"{""Item Form"": ""Stick"", ""Color"": ""Beige"", ""Pack...",2017,6,1,3,1,False
2,5.0,Love This..made my mom's day,My 90 year old mother's favorite fragrance.,B01IAFGDYS,B01IAFGDYS,AFTDHU6IXXYGCEJ6JUAI7LFD3JMA,2019-06-24 16:14:04.340,0,True,All Beauty,...,7,NaN,Five Star,"{""Brand"": ""Five Star"", ""Item Form"": ""Spray"", ""...",2019,6,24,0,16,False
3,1.0,Review,Just not worth it,B01DX9HUP2,B01DX9HUP2,AGIEEQAKFGKN7JH4LQKRWTCCMXGA,2017-06-15 21:07:17.278,0,True,All Beauty,...,239,NaN,Buytra,"{""Brand"": ""Buytra"", ""Recommended Uses For Prod...",2017,6,15,3,21,False
4,5.0,Battery will not stay charged (Rescinding),The Battery life on this product has always be...,B07W11NLFS,B07W11NLFS,AFNEEMO6DSJJTMBCIF3SCXUQBH2A,2020-01-27 14:58:37.959,1,True,All Beauty,...,574,NaN,Duomishu,"{""Brand"": ""Duomishu"", ""Power Source"": ""Battery...",2020,1,27,0,14,False

In [105]:
df_clean.tail()

,rating,title_review,text,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,main_category,...,rating_number,price,store,details,review_year,review_month,review_day,review_day_of_week,review_hour,price_available
19995,5.0,Great,Its worth it.,B08LMWJLSD,B08LMWJLSD,AHAFV6OJ3O4FDZN76YOAG3GWL6RQ,2021-01-27 22:41:15.088,0,True,All Beauty,...,91,NaN,As always,"{""Material"": ""Carbon Fiber"", ""Brand"": ""As alwa...",2021,1,27,2,22,False
19996,1.0,Not worth it,"Don’t work like on the comerciales and videos,...",B08QMJLMCQ,B08QMJLMCQ,AFSYRQNBFP5RXLXOFXNKMCQGYDEQ,2021-03-11 00:15:56.090,2,True,All Beauty,...,1479,NaN,MAITING,"{""Brand"": ""MAITING"", ""Item Form"": ""Clay"", ""Pro...",2021,3,11,3,0,False
19997,5.0,It works!,"Worked for us, is a lil difficult to put on bu...",B019FT4ELC,B019FT4ELC,AENRI343SRCQ3OG5WXVXPGIZOZVA,2016-11-09 19:14:49.000,1,True,All Beauty,...,45,6.95,Savvi,"{""Brand"": ""Savvi"", ""Water Resistance Level"": ""...",2016,11,9,2,19,True
19998,2.0,Two Stars,brush is good only complain i have is that the...,B010U82WRU,B010U82WRU,AEATBVC7X6W466747I3XO3FP4KPA,2015-12-17 17:50:41.000,0,True,All Beauty,...,177,NaN,HOSL,"{""Brand"": ""HOSL"", ""Recommended Uses For Produc...",2015,12,17,3,17,False
19999,5.0,Jade color,Really lovely color! Better than the picture ...,B01LWP22Z3,B07XDCCFF9,AEWL67VNSJ7KF5XN4GWMO4FSKDEA,2020-06-15 23:55:56.894,0,True,All Beauty,...,502,11.95,Camila,"{""Brand"": ""Camila"", ""Hair Type"": ""Small, Poor,...",2020,6,15,0,23,True

In [106]:
df_clean.to_parquet(
    "../data/processed/marketplace_cleaned.parquet",
    index=False
)

In [107]:
import os

os.path.exists("../data/processed/marketplace_cleaned.parquet")

True